# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30, unique=True)),
                ('gender', models.CharField(max_length=6)),
                ('language', models.CharField(max_length=2)),
            ],
        ),
    ]
